[data]
x = "x_location"
y = "y_location"
z = "z_location"
gene = "feature_name"
min_molecules_per_gene = 5
# 16 bit exclusion
# exclude_genes = "Blank*, OR10C1, OR10G2, OR10H1, OR10H5, OR10Q1, OR10S1, OR10W1, OR11A1, OR12D1, OR13A1, OR13J1, OR1F1, OR1I1, OR1M1, OR2A1, OR2A14, OR2A20P, OR2A4, OR2A42, OR2A9P, OR2AT4, OR2B11, OR2C1, OR2C3, OR2F1, OR2H1, OR2H2, OR2L13, OR2S2, OR2T2, OR2T27, OR2T35, OR2T5, OR2T7, OR2Z1, OR3A2, OR3A3, OR3A4P, OR51D1, OR51E1, OR51E2, OR51G1, OR52I1, OR52I2, OR52K2, OR52L1, OR52W1, OR56B1, OR56B4, OR5AU1, OR5C1, OR6A2, OR6J1, OR6W1P, OR7A5, OR8A1, OR9Q1"
# 22 bit exlcusion
# exclude_genes = "Blank*, OR1I1"
#OR10A2, OR10A6, OR10AC1, OR10C1, OR10D3, OR10G7, OR10H5, OR10J1, OR10K1, OR10K2, OR10W1, OR10Z1, OR11A1, OR12D3, OR13A1, OR14I1, OR1A1, OR1B1, OR1C1, OR1I1, OR1L8, OR1S1, OR2A5, OR2AG1, OR2AJ1, OR2AP1, OR2C1, OR2G6, OR2H2, OR2I1P, OR2J2, OR2J3, OR2L13, OR2L2, OR2M3, OR2M4, OR2T12, OR2T2, OR2T6, OR2V1, OR2V2, OR2W5P, OR2Z1, OR3A3, OR4D1, OR4D10, OR4D9, OR4K13, OR4K17, OR4M1, OR4N2, OR4N5, OR4S2, OR51A4, OR51C1P, OR51D1, OR51E1, OR51G2, OR51L1, OR51M1, OR52A1, OR52A5, OR52D1, OR52E5, OR52I2, OR52N1, OR56A1, OR56A3, OR56B2P, OR5A1, OR5AN1, OR5AS1, OR5B2, OR5D3P, OR5H1, OR5K1, OR5M1, OR5T2, OR6A2, OR6B1, OR6C74, OR6K3, OR6N1, OR6N2, OR6P1, OR6Y1, OR7A5, OR7C1, OR8A1, OR8B8, OR8D4, OR8G1, OR8K3, OR9G1, OR9H1P, OR9Q2"
min_molecules_per_cell = 20

[segmentation]
unassigned_prior_label = "1"
prior_segmentation_confidence = 0.7

[plotting]
min_pixels_per_cell = 15 # Number of pixels per cell of minimal size, used to estimate size of the final plot. For most protocols values around 7-30 give enough visualization quality. Default: 15
max_plot_size = 5000 # Maximum size of the molecule plot in pixels. Default: 5000